# Generated by Django 3.0.6 on 2020-05-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150, null=True, verbose_name='Full Name')),
                ('blood_group', models.CharField(max_length=150, null=True, verbose_name='Blood Group')),
                ('birth_date', models.TimeField(max_length=150, null=True, verbose_name='Date of Birth')),
                ('phone', models.CharField(max_length=150, null=True, verbose_name='Phone Number')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('patient_email', models.EmailField(max_length=150, null=True, verbose_name='Email')),
                ('status', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
