# Generated by Django 3.0.6 on 2020-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='birth_date',
            field=models.DateField(max_length=150, null=True, verbose_name='Date of Birth'),
        ),
    ]
