# Generated by Django 3.0.6 on 2020-05-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_auto_20200526_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='image',
        ),
    ]
