# Generated by Django 3.0.6 on 2020-05-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_remove_patients_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
