# Generated by Django 3.0.6 on 2020-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_auto_20200527_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='patient_email',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='status',
        ),
        migrations.AddField(
            model_name='patients',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=150, null=True, verbose_name='Gender'),
        ),
    ]
