# Generated by Django 3.0.6 on 2020-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_auto_20200527_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(max_length=150, null=True, verbose_name='Gender')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('update_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='description',
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='patients',
            name='birth_date',
            field=models.DateField(max_length=150, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(max_length=150, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='patients',
            name='fullName',
            field=models.CharField(max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.CharField(max_length=150, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='patients',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
