# Generated by Django 3.0.6 on 2020-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_auto_20200527_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='description',
            field=models.TextField(default='Enter'),
        ),
    ]
