# Generated by Django 3.0.6 on 2020-05-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0009_auto_20200527_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='description',
        ),
    ]
