# Generated by Django 3.0.6 on 2020-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_auto_20200527_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='casehistory',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
