# Generated by Django 3.0.6 on 2020-05-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_auto_20200527_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Patients', verbose_name=''),
        ),
    ]
