# Generated by Django 3.0.6 on 2020-05-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0016_auto_20200527_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=150, null=True, verbose_name='Invoice')),
                ('patient_name', models.CharField(max_length=150, null=True, verbose_name='Patients Name')),
                ('service', models.CharField(max_length=150, null=True, verbose_name='Service')),
                ('Service_Cost', models.CharField(max_length=150, null=True, verbose_name='Service Cost')),
                ('amount_recieved', models.CharField(max_length=150, null=True, verbose_name='Amount Recieved')),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='status',
        ),
        migrations.AddField(
            model_name='casehistory',
            name='case_status',
            field=models.CharField(choices=[('treated', 'Diagonised'), ('not diagonised', 'Not Diagonised')], default='Not Diagonised', max_length=20),
        ),
        migrations.AddField(
            model_name='patients',
            name='case_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_names', to='hms.Patients'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.CharField(max_length=150, null=True, verbose_name='Amount Deposited')),
                ('service_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Payments', verbose_name='service_invoice')),
            ],
        ),
    ]
