# Generated by Django 3.0.6 on 2020-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0017_auto_20200529_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='case_status',
        ),
        migrations.AddField(
            model_name='patients',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='case_status',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
