# Generated by Django 3.0.6 on 2020-05-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0018_auto_20200529_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='case_status',
        ),
    ]
