# Generated by Django 3.0.6 on 2020-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0021_auto_20200529_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='patient',
            field=models.CharField(max_length=150, null=True, verbose_name='Ptients Name'),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='case_status',
            field=models.CharField(choices=[('------', '-------'), ('Diagnosed', 'Diagnosed'), ('Not Diagnosed', 'Not Diagnosed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.CharField(choices=[('------', '-------'), ('Active', 'Active'), ('In-Active', 'In-Active')], default='---', max_length=20),
        ),
    ]
