# Generated by Django 3.0.6 on 2020-05-30 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0022_auto_20200529_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
