# Generated by Django 3.0.6 on 2020-05-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0023_casehistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='date',
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='patient',
            field=models.CharField(max_length=150, null=True, verbose_name='Patients Name'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.CharField(max_length=150, null=True, verbose_name='Temprature')),
                ('blood_pressure', models.CharField(max_length=150, null=True, verbose_name='Blood Pressure')),
                ('schedule_update', models.DateTimeField(auto_now=True, null=True)),
                ('scheduled_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='hms.Patients')),
            ],
        ),
    ]
