# Generated by Django 3.0.6 on 2020-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0025_auto_20200530_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='patient_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Patients'),
        ),
    ]
